### ISSUE TITLE
Feature Request: Typescript Support

### ISSUE THREAD

**Issue by georgeedwards** [feathersjs/cli#114]
Is there any interest in supporting Typescript with the cli. As documented in the issue on the main repo, [TypeScript](https://github.com/feathersjs/feathers/issues/381) support is workable and improving. 

I think the missing piece for TS support is the CLI. I just wanted to gauge interest, as I would be happy to contribute to this. 

If so, what would be the ideal approach:

```
>yo feathers-ts
? Project name test-proj
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? Yarn
? What type of API are you making? REST, Realtime via Socket.io
```

or one generator with a language option?

```
>yo feathers
? Project name test-proj
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? Yarn
? Which language would you like to use? TypeScript
? What type of API are you making? REST, Realtime via Socket.io
```

My preference would be the second one, although this is a slightly less convinient to implement.

**Comment by j2L4e** [comment]
I looked into this before and the main problem I found was that `jscodeshift` used in `generator-feathers` can't traverse TypeScript. Thus adding TS support to the generator seemed far more complicated than I had anticipated.

Maybe this would be easier to accomplish with `feathers-generator`? What's the progress of that?
cc @slajax because he's the `feathers-generator` guy

**Comment by georgeedwards** [comment]
@j2L4e If you see my [fork](https://github.com/georgeedwards/generator-feathers/tree/typescript) of the yeoman generator, thta is where I have started.

**Comment by slajax** [comment]
@j2L4e we can certainly take a look at adding this into the v3 generator. It effectively doesn't do any sort of in place code manipulation so it's ideal for these sorts of scenarios. There are still a number of tasks open before v3 is stable and I would love some additional eyes on it.

**Comment by georgeedwards** [comment]
@slajax Does that mean v3 is removing the jscodeshift stuff?

**Comment by slajax** [comment]
It currently does but that doesn't implicitly mean it will be published to the community or replace v2. The shift from jscodeshift to configuration files seems like it will be a pretty big leap for the community and that trade off isn't as beneficial to new users as for power users so we haven't released it for this reason. I currently use it in a number of production applications and I believe others may as well but we haven't made any plans to formally release it so it's sort of plateaued, although my team and I are ramping it back up this week coincidentally because it's core to our products. You can a look at it by npm linking feathers-generator v3 branch into feathers-cli 3.0 branch. Would appreciate any feedback - heads up, it lacks documentation right now. This issue might be a reasonable catalyst for pushing harder on it but I know we weren't officially supporting type script bindings in core so this would still probably fall into user land as an advanced feature. Check it out though, it's definitely a solution to this problem but it's not clear how we can bridge the compromises above for the community so we basically decided to punt for now.

**Comment by slajax** [comment]
cc @otang

**Comment by georgeedwards** [comment]
There isn't a v3 branch of the [generator-feathers](https://github.com/feathersjs/generator-feathers/branches) project?

**Comment by slajax** [comment]
Sorry, it's a different repo: feathersjs/feathers-generator - not yeoman naming.

**Comment by georgeedwards** [comment]
@slajax OK, so if I am correct, the v3 project moves from yeoman to metalsmith, and just generates new files, rather than adding imports etc. ?

**Comment by slajax** [comment]
Yes. It also leverages daffl/fathers-bootstrap to configure the app and each service at runtime.

**Comment by georgeedwards** [comment]
How does it work exactly? It says it is used by the feathers-cli? Does it run on it's own? What steps are required to generate a new app from the command line?

**Comment by slajax** [comment]
You have to npm link feathers-generator v3 branch into the 3.0 branch on feathers-cli then run the feathers executable in bin. Check pull requests for examples on the command interface. Unfourtunately though, we have decided to sunset the generator, so I wouldn't put much effort into it. It won't be released.

**Comment by georgeedwards** [comment]
Oh, is that just the metalsmith v3? or the standard version?

**Comment by slajax** [comment]
Lets move this conversation out of the issue thread. We're probably blowing up everyones inbox. Hit me up on Slack via DM if you wanna chat about this more @georgeedwards

**Comment by ScreamZ** [comment]
The only issue I see for now is that i'm getting this

**Comment by snewell92** [comment]
Could be related to #88 

Part of the purpose of yeoman generator configuration is specifying a language (example [on their docs is for coffeescript](http://yeoman.io/generator/Storage.html)).

**Comment by murbanowicz** [comment]
Is there anything going on with that or not?
It would be so great to be able to generate the Feathers app with TypeScript out of the box

**Comment by daffl** [comment]
Probably not at the moment. There is quite a bit of work involved in updating the codemods to work with TS and/or ES modules. There are three options:

1. Fork the generator and try updating the generated code to TS. Unless you get the codemods updated as well this will probably mean that with a TS generator you have to wire up generated hooks and services manually.
2. Wait for someone else to do it - we had two people do some great work around TypeScript but in general getting any actual help from the TypeScript "community" has been a big challenge
3. Wait for me to find the time to update the codemods to support ES modules and TS - this will probably happen when the latest version of Node officially ships with ES module support

**Comment by daffl** [comment]
Closing since a TypeScript option is now available in the [Feathers+ CLI](https://generator.feathers-plus.com/)

**Comment by rayfoss** [comment]
... Well I put together an ES Modules boilerplate with all the bugs (mocha, module-alias, semicolons, reserved keywords) worked out https://github.com/rayfoss/feathers-boilerplate-esm

wish I had known about the Typescript generator... perhaps the docs should deprecate @feathersjs/cli

**Comment by daffl** [comment]
Full TypeScript support is now also available in Feathers v4 and the `@feathersjs/cli`. It will not be drecreated.

**Comment by wagerfield** [comment]
@daffl this is huge, thank you! 🎉
