### ISSUE TITLE
generate always creates files inside src. What if i want to change  that default?

### ISSUE THREAD

**Issue by ramstein74** [feathersjs/cli#153]
generate always creates files inside src. What if i want to change  that default?

I´m using create-nuxt-app that does not use src folder . Instead have a server folder where feathers in located.
When i do
feathers generate inside server folder it creates a src folder and inside the new service for example.
I just want generate to use the current folder instead.

How do i do that?
regards

**Comment by daffl** [comment]
You can modify the folder by changing [directories.lib in you package.json](https://github.com/feathersjs/feathers-chat/blob/master/package.json#L17).

**Comment by aslikyan** [comment]
I see the issue is closed but if your problem similar to this but you don't want to change the default configuration you can just specify the service name with the path. For example, if you want to generate a service in the `example`  folder inside the services(default) folder, in the 2nd question when you specify the name of the service specify like this `example/service-name`
