### ISSUE TITLE
[3.0] Have a basic "doctor" command

### ISSUE THREAD

**Issue by ekryski** [feathersjs/cli#24]
A lot of people seem to get hung up because their environment is either a bit broken or isn't setting up really well for Feathers.

A good place to start might be to have a `doctor` command that inspects their env when they generate a project. This is what I'm thinking:
### Basic

This is some of the basic stuff we probably should check.
- [x] Check that node exists
- [x] Check that npm exists
- [x] Check for node v5.x+, prompt for upgrade if not
- [x] Check for npm v.3.8.7+, prompt for upgrade if not
### More Advanced

This is stuff that would be nice but definitely isn't crucial from day one.
- [ ] Check that project name isn't the same as a dependency
- [ ] Check that all the dependencies are installed
- [ ] Check for node_gyp (ie. that we can compile binaries)
- [ ] Check gcc version?
- [ ] Check `feathers.json` is valid
- [ ] Check/print out environment variables
### Inspiration
- [Homebrew Doctor](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/doctor.rb) and it's [checks](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/diagnostic.rb)
- [Yeoman doctor](https://github.com/yeoman/doctor)

**Comment by jdhines** [comment]
This would be great. All I've done is install `feathers-cli` and run `feathers generate` and after answering the questions, it's just completely hung up, won't even create the initial files. I bet it has to do with my network setup at work with the proxy, but I have my NPM proxies set. How do I go about troubleshooting what to do, because I'm stuck on Step #1 of creating a FeathersJS app!
